export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// RootLayoutは特殊な関数であり、app.jsの内容をchildrenとして読み込める。
// テンプレートの役割を持つ
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
